autometrics-dev/autometrics-ts

packages/autometrics/src/wrappers.ts
For reference:
https://nodejs.org/api/perf_hooks.html#performancenow
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now
=> Replace `new Date.now()` with `performance.now()`

.gitignore, README.md, examples/express/package.json, examples/express/tsconfig.json, examples/fastify/package.json, examples/fastify/tsconfig.json, examples/nestjs/.prettierrc, examples/nestjs/package.json, examples/nestjs/tsconfig.json, package-lock.json, package.json, packages/autometrics-typescript-plugin/README.md, packages/autometrics-typescript-plugin/package.json, packages/autometrics-typescript-plugin/tsconfig.json, packages/autometrics/README.md, packages/autometrics/package.json, packages/autometrics/tsconfig.json, rome.json, tsconfig.common.json, vite.config.ts
Prevents mixing of tabs & spaces indentation when manually editing these files.
=> Replace tabs with 2 space indentation on remaining files

README.md, packages/autometrics-typescript-plugin/src/astHelpers.ts
Round of refactoring and improving code readability in `astHelpers`. Also fixes the TypeScript name in the project's README.
=> TypeScript plugin improvements

packages/autometrics/src/instrumentation.ts, packages/autometrics/src/wrappers.ts
Keep comments withing 80 character limit where possible & minimal refactoring.
=> Formatting in `autometrics` package

README.md, examples/fastify/src/index.ts, package-lock.json, packages/autometrics-typescript-plugin/package.json, packages/autometrics/package.json
- fix formatting
- bump version number to 0.1
=> formatting fix and version bump for initial release

package.json, packages/autometrics-lib/package.json, packages/autometrics-typescript-plugin/package.json, packages/autometrics/package.json
- fix fmt
- bump patch version and release fix for plugin
=> bump to v0.1.2 and release convenience package autometrics

examples/react-app/package.json, examples/react-app/prometheus.yml, examples/react-app/src/App.tsx, examples/react-app/tsconfig.json
Simplifies the React example by only fetching a single post entry.
Also adds a README reference to the usage of wrappers client-side.
=> Update React example

package-lock.json, packages/autometrics/package.json
Resolves https://github.com/autometrics-dev/autometrics-ts/issues/35
=> Add `@opentelemetry/api` as dependency of `autometrics` package

CHANGELOG.md, examples/express/package.json, examples/fastify/package.json, examples/nestjs/package.json, examples/react-app/package.json, examples/svelte-app/package.json, package-lock.json, packages/lib/package.json, packages/typescript-plugin/package.json
- update package.jsons
- update example package.jsons
- update CHANGELOG
=> Release v0.4

CHANGELOG.md, examples/express/package.json, examples/fastify/package.json, examples/nestjs/package.json, examples/react-app/package.json, examples/svelte-app/package.json, package-lock.json, packages/autometrics/package.json, packages/lib/package.json, packages/lib/src/buildInfo.ts, packages/lib/src/instrumentation.ts, packages/lib/tests/buildInfo.test.ts, packages/typescript-plugin/package.json
- bump version number on package.jsons
- bump example package.jsons
- update changelog
=> Release v0.5.0

packages/autometrics/package.json, packages/lib/package.json, packages/typescript-plugin/package.json
=> Update npm scripts

.github/workflows/publish_lib_to_npm.yml, .github/workflows/publish_parcel_plugin_to_npm.yml, .github/workflows/publish_typescript_plugin_to_npm.yml
Make sure the tools really are available on CI.
=> Install Rome CLI tools

CHANGELOG.md, CONTRIBUTING.md, examples/express/package-lock.json, examples/express/package.json, examples/express/src/util.ts, packages/lib/src/instrumentation.ts, packages/lib/src/wrappers.ts
> Fixes #102 
Before:
```
function_calls_duration_bucket{function="handleGetUserById",module="/dist/server.js",le="0"} 0 1689767351156
function_calls_duration_bucket{function="handleGetUserById",module="/dist/server.js",le="5"} 1 1689767351156
function_calls_duration_bucket{function="handleGetUserById",module="/dist/server.js",le="10"} 1 1689767351156
function_calls_duration_bucket{function="handleGetUserById",module="/dist/server.js",le="25"} 1 1689767351156
function_calls_duration_bucket{function="handleGetUserById",module="/dist/server.js",le="50"} 1 1689767351156
function_calls_duration_bucket{function="handleGetUserById",module="/dist/server.js",le="75"} 1 1689767351156
function_calls_duration_bucket{function="handleGetUserById",module="/dist/server.js",le="100"} 1 1689767351156 …
```
=> Modify histogram buckets to play nicely with seconds

CHANGELOG.md, packages/autometrics/package.json, packages/lib/package.json, packages/typescript-plugin/package.json
This PR updates changelog and relevant `package.json` information for a new release.
=> Prepare new release for lib and ts-plugin

examples/express/package.json, examples/faas-experimental/package.json, examples/fastify/package.json, examples/nestjs/package.json, examples/react-app-experimental/package.json, packages/autometrics/package.json, packages/exporter-otlp-http/package.json, packages/exporter-prometheus-push-gateway/package.json, packages/exporter-prometheus/package.json, yarn.lock
Prepares us to release 0.7.0 of the libraries 🎉
=> Update package versions and dependencies to 0.7.0

examples/express/package.json, examples/faas-experimental/package.json, examples/fastify/package.json, examples/hono-bun/package.json, examples/nestjs/package.json, examples/react-app-experimental/package.json, packages/exporter-prometheus-push-gateway/package.json, packages/exporter-prometheus/package.json, yarn.lock
Final fixes and tweaks before publishing `0.7.*` of newest packages
=> Publish 0.7.* of core and exporters

.github/workflows/publish_lib_to_npm.yml
- set up bun for runtime test
- add build command for publishing
=> Fix library publishing Github action

packages/typescript-plugin/justfile, scripts/build_npm.ts
=> Add minimum Node version requirement

packages/autometrics/src/objectives.ts
=> Warn on invalid objective name

CONTRIBUTING.md, examples/fastify/yarn.lock, examples/react-app-experimental/yarn.lock, package.json, packages/autometrics/src/exporter-prometheus/PrometheusExporter.ts, packages/autometrics/tests/otlpHttpExporter.test.ts, packages/autometrics/tests/testUtils.ts
=> Update version number
