autometrics-dev/autometrics-ts

- .github/workflows/publish_to_npm.yml
- packages/autometrics-typescript-plugin/package.json
- packages/autometrics/package.json
Existing Github workflow publishes all packages without building it prior.
This fixes it
- make sure to build before publish
- bump hotfix release
> Fix publishing workflow

- packages/autometrics-typescript-plugin/src/astHelpers.ts
The previously written logic didn't correctly check for undefined values in a helper function resulting to TypeScript attempting to run a `isMethod` checker on undefined values and erroring out. This fixes that.
> Fix: typescript plugin err

- README.md
- examples/express/src/index.ts
- examples/react-app/package.json
- examples/react-app/src/App.tsx
- examples/react-app/tsconfig.json
- package-lock.json
- packages/autometrics-lib/README.md
- packages/autometrics-lib/tsconfig.json
- packages/autometrics-typescript-plugin/src/index.ts
- packages/autometrics-typescript-plugin/tsconfig.json
- packages/autometrics/README.md
- packages/autometrics/package.json
- packages/autometrics/src/index.ts
- packages/autometrics/tsconfig.json
- tsconfig.common.json
This PR removes the TypeScript plugin from the convenience package. This is to
ensure that the main library can use ESM 
- removes autometrics plugin from the convenience package
- update tsconfig: use ESM in the main library, continue to use CJS in plugin
- update docs
- package-lock update
> Removes TypeScript plugin from the convenience package

- README.md
Simple README tweaks. 
The most important change is a fix for the code sample that shows how to configure the exporter that's passed to `init`
> Fix a code sample in README and tweak some copy

- examples/express/src/index.ts
- package-lock.json
- package.json
- packages/autometrics-lib/src/wrappers.ts
- packages/autometrics-lib/tests/objectives.test.ts
- packages/autometrics-lib/tests/util.ts
- packages/autometrics-typescript-plugin/src/utils.ts
Updates `rome` to `12.0.0` and `vitest` to `0.30.1` and includes fixes for the new linter rules.
> Update rome and vitest

- README.md
Simple PR. The README stated that Grafana Dashboards were "Coming soon", but in fact we have a shared repo with the JSON you need to set them up.
> Add link to Grafana dashboards in README

- .vscode/launch.json
- CONTRIBUTING.md
- examples/react-app/.gitignore
- examples/svelte-app/.gitignore
This PR adds simple `launch.json` configs that will help make debugging
TypeScript plugin easier. The two commands:
1. Launch VSCode (for debugging) - launches a simple VSCode instance (no
extensions running) with a breakpoint configured on port `9229` that a
debugger can attach to.
2. Attach VSCode - attaches the host VSCode to the running "guest" VSCode
- remove gitignores that were intruding
- add launch.json config
- update docs
> Add launch.json configs for easier TypeScript debugging

- README.md
- examples/nestjs/package.json
- examples/nestjs/src/app.service.ts
- packages/autometrics-lib/src/utils.ts
- packages/autometrics-lib/src/wrappers.ts
- packages/autometrics-typescript-plugin/src/astHelpers.ts
- packages/autometrics-typescript-plugin/src/utils.ts
Introduces an `@Autometrics()` decorator that can be applied to both a class or class method.
- Instruments all methods defined in a class when applied to a class;
- Decorator accepts an `AutometricsOptions` object like the general function wrapper;
- Update README & NestJS examples;
- Update the TypeScript plugin displaying the instrumented methods when hovering;
- Move helper logic to `utils.ts` in both the TypeScript plugin & general autometrics libs;
- Add breaks at 80-character limit where possible in files I've been working in.
Current known issues (to be picked up after this PR):
- The decorator accepts the `AutometricsOptions` object, including its `functionName` property. This should be prevented when decorating a class as it often has multiple methods - which will be interpreted …
> Add support for applying autometrics decorator to classes

- packages/autometrics-lib/src/utils.ts
- packages/autometrics-lib/src/wrappers.ts
The decorator currently accepts an `AutometricsOptions` object, that includes the `functionName` property. When decorating a class we're now omitting this option as this property should only be set on single functions/methods.
```typescript
@Autometrics()
class Foo {
bar() {}
}
class Bar {
@Autometrics()
baz() {}
}
```
> Improve `@Autometrics()` decorator type signature

- README.md
- packages/autometrics-lib/src/buildInfo.ts
- packages/autometrics-lib/src/instrumentation.ts
- packages/autometrics-lib/src/wrappers.ts
- packages/autometrics-lib/tests/integration.test.ts
- packages/autometrics-typescript-plugin/src/index.ts
- packages/autometrics-typescript-plugin/src/queryHelpers.ts
Resolves #45 
This update adds `build_info` data to the metrics exported. Whenever the first
`autometrics` wrapper is called it will create an object that will persisting
through the runtime and report version, commit, and branch data (depending on
what is supplied). The data can be supplied through env variables:
version: picked up automatically if the package is run through `npm`, `yarn`, or
`pnpm`, - can be manually supplied through `PACKAGE_VERSION` or `AUTOMETRICS_VERSION` otherwise.
commit: must be supplied through `COMMIT_SHA` or `AUTOMETRICS_COMMIT` env variable
branch: must be supplied through `BRANCH_NAME` or `AUTOMETRICS_BRANCH` env variable
The update also fixes a previous functionality that would throw an error if a
function without a name was supplied. It will now just log a …
> Add build_info data

- packages/lib/src/buildInfo.ts
- packages/lib/src/instrumentation.ts
- packages/lib/src/wrappers.ts
- packages/lib/tests/buildInfo.test.ts
- fix: actually make sure build_info gets properly recorded (previously it would read empty object)
- add buildinfo unit test
> Properly fix `build_info` and add a unit test

- packages/typescript-plugin/package.json
- packages/typescript-plugin/src/astHelpers.ts
This small PR fixes a few issues I ran into with the TS plugin that would crash the TypeScript Language Service.
- add runtime type guard for when passed in node is a SourceFileObject
- add optional chaining to fix issues where JS process would attempt accessing values that didn't exist
- bump fix version for release
> Fix TS plugin errors

- packages/lib/src/utils.ts
- packages/lib/tests/utils.test.ts
The module getter utility that parses the stack trace was silently failing and returning "file" in all cases. This fixes it by correctly replacing `file://` prefix and adds a unit test for the function
- fix module getter to correctly replace the file:// prefix along with the rootDir
- add a unit test for the module getter
> Fix module getter utility

- examples/express/src/index.ts
- packages/typescript-plugin/src/index.ts
- packages/typescript-plugin/src/queryHelpers.ts
While playing with the sample apps, I noticed that the TypeScript plugin was generating wrong queries. Some PromQL queries were false while others were outright broken. This PR rectifies that:
- uses `function_calls_` regex to grab the Autometrics-instrumented metrics
- correctly inserting `function` as opposed to `caller` where it should
- fixing up some templates that had PromQL syntax errors
> Fix PromQL errors

- packages/parcel-transformer-autometrics/package.json
Sets the Parcel plugin version to publish initial version.
> Set Parcel plugin version to 0.1.0

- CHANGELOG.md
- packages/typescript-plugin/package.json
- packages/typescript-plugin/src/astHelpers.ts
- packages/typescript-plugin/src/index.ts
- packages/typescript-plugin/src/types/index.ts
This is done by tweaking the logic slightly (typescript 5 returns a slightly different AST tree) and also use the typescript util functions that are passed into the plugin. This is important because the vscode extension currently bundles a typescript version which might be different from the one that the project is using. And given that typescript relies on enums with numbers, we can run into issues where the value 357 for SyntaxKind might mean one thing in one version and something completely different in another typescript version.
> Fix typescript plugin with typescript 5 

- packages/parcel-transformer-autometrics/package.json
Quick change to make sure the publish workflow is being triggered on the CI for the new Parcel plugin
> Bump version for the Parcel plugin

- README.md
This update adds a reference to the Autometrics CLI for a faster workflow to preview instrumented metrics.
> Add references to the AM CLI in the README

- CHANGELOG.md
- packages/lib/src/utils.ts
- packages/lib/src/wrappers.ts
- packages/lib/tests/integration.test.ts
This PR fixes several issues:
- Decorators were throwing out `this` values for the methods they were wrapping. Core wrapper `autometrics` now uses `Function.apply` to preserve the `this` context.
- Using `Function.apply` also doesn't require copying all of the parameters using the spread operator which should reduce memory footprint for functions that have large parameter objects they're passing around.
- Refactors `getModulePath` utility: it now constructs a custom stack trace with only the necessary information to get the filename without string parsing.
It also adds a test to ensure decorators work properly.
> Refactor `getModulePath` and fix decorator errors

- CHANGELOG.md
- packages/lib/src/wrappers.ts
> Related to discussion: https://github.com/orgs/autometrics-dev/discussions/21
This PR enables wrapped functions and decorators to initialize counters at 0.
This will allow tooling that connects to Prometheus to be able to tell which functions are being tracked, even if those functions haven't been called since adding Autometrics to the codebase.
> Initialize counters at zero

- packages/lib/src/utils.ts
- packages/lib/src/wrappers.ts
> Note: the PR seems sizeable but most of the action is happening in the `wrappers.ts` file. The rest is just example apps updates.
This PR is an initial implementation of the issue raised in #82 - ensuring that Autometrics wrapper can correctly record errors even if they are handled in the wrapped original handling. It also adds the ability to record successes even if the original wrapped function threw an error which is useful for cases when the thrown errors should be ignored.
Both conditions are added as `recordErrorIf` and `recordSuccessIf` callbacks to the `AutometricsOptions` object optionally placed in the first parameter place.
Given a function `createUser` that (importantly) _returns_ a status code 201 on successful POST request:
```typescript
async function createUser(user: …
```
> Add `recordErrorIf` and `recordSuccessIf` callbacks

- packages/lib/src/buildInfo.ts
- packages/lib/src/constants.ts
- packages/lib/src/wrappers.ts
- packages/lib/tests/integration.test.ts
- packages/lib/tests/objectives.test.ts
This PR updates metric names according to the latest versions of the spec and adds descriptions for them.
> Rename metrics to spec and add descriptions

- packages/lib/reference/README.md
- packages/lib/reference/enums/ObjectiveLatency.md
- packages/lib/reference/enums/ObjectivePercentile.md
Previous PR that merged the functionality didn't include the regenerated docs - this fixes that.
> Update API reference for `recordErrorIf` and `recordSuccessIf` callbacks

- packages/lib/src/wrappers.ts
Per [the spec](https://github.com/autometrics-dev/autometrics-shared/blob/f6f084ad1391ed1ad9de5c484cfa836a8311fcf6/SPEC.md?plain=1#L92), `autometrics-ts` should report histogram in seconds units as opposed to ms. Closes #93
> Use seconds instead of milliseconds for histograms

- packages/lib/reference/README.md
- packages/lib/reference/enums/ObjectiveLatency.md
- packages/lib/reference/enums/ObjectivePercentile.md
- packages/lib/src/buildInfo.ts
- packages/lib/src/index.ts
- packages/lib/src/instrumentation.ts
- packages/lib/src/objectives.ts
- packages/lib/src/wrappers.ts
- packages/lib/typedoc.json
This PR improves documentation by adding better doc comments, grouping related functions and interfaces. It also updates the typedoc configuration to exclude interfaces marked as internal. Finally it commits the updated generated reference.
Closes #96
> Improve API reference

- packages/typescript-plugin/src/astHelpers.ts
- packages/typescript-plugin/src/index.ts
Closes #91 
This PR fixes an issue where Autometrics hover wouldn't show in cases like this:
```typescript
autometrics(wrappedFunction)
^ -- hovering here
```
Basically it simplifies some redundant logic that prevented the tooltip for showing.
> Fix TS Plugin: show hover in wrapped functions

- packages/lib/src/buildInfo.ts
- packages/lib/src/instrumentation.ts
- packages/lib/src/wrappers.ts
- packages/lib/tests/buildInfo.test.ts
- packages/lib/tests/objectives.test.ts
This is a change to support autometrics-ts when used with the gravel aggregation gateway. 
Aggregating a gauge like `build_info` requires a special label.
We want to clear previous build_info metrics when new ones are pushed. 
Grave Gateway requires that you add a `clearmode` label to do this.
Gravel Gateway will reject two metrics of the same name if one of them has a subset of the labels of the other.
This means to be able to support functions that have objectives, as well as functions that don't, we need to default to setting the `objective_*` labels to the empty string.
- Add support for specifying the job name
- Check that pushing build_info with a new job name does not clear all existing build_info metrics with different job names
> Initial Gravel Gateway Support

- examples/react-app-experimental/src/App.tsx
- packages/exporter-otlp-http/src/index.ts
Also re-exports the `AggregationTemporalityPreference`, so people can directly use it.
> Use delta temporality for React example

- examples/express/src/server.ts
- examples/fastify/src/index.ts
- examples/nestjs/src/main.ts
- packages/autometrics/README.md
- packages/exporter-prometheus/README.md
- packages/exporter-prometheus/src/index.ts
The `PrometheusExporter` from `"@opentelemetry/exporter-prometheus"` uses port `9464` as a default. 
I've updated our examples, docs, and prometheus exporter library to reflect that default.
> Fix default prometheus exporter port

- packages/autometrics/src/temporaryMeter.ts
This fixes the issue where sometimes the warning gets displayed even though `init()` has been called successfully.
> Clear timer on handover

- packages/typescript-plugin/package.json
- packages/typescript-plugin/src/astHelpers.ts
- packages/typescript-plugin/src/index.ts
- packages/typescript-plugin/src/types/nodeType.ts
This is a patch for a couple of issues that made TypeScript plugin render empty quick info tooltips.
Note: this is a hotfix intended to be published under the `beta` tag and warrants a thorough revision before going into the general release
> Patch TypeScript plugin 

- biome.json
- examples/express/tests/callerInfo.test.ts
- examples/hono-bun/tests/callerInfo.test.ts
- packages/autometrics/src/platform.deno.ts
- packages/autometrics/src/platform.node.ts
- packages/autometrics/src/wrappers.ts
- packages/autometrics/tests/__snapshots__/otlpHttpExporter.test.ts.snap
- packages/autometrics/tests/callerInfo.test.ts
This PR updates the library so it correctly reports the `caller_function` and `caller_module` information as per spec.
> Add caller.function and caller.module labels

- packages/autometrics/src/constants.ts
- packages/autometrics/tests/__snapshots__/otlpHttpExporter.test.ts.snap
- tsconfig.json
This merely changes all the label constants to use dots instead of underscores, so they get submitted to OTLP endpoints according to the 1.0 spec.
I didn't have to change anything for the Prometheus exporters, because it appears the libraries do the translation back to underscores for us (and we have test coverage for it).
Implements AM-46.
> Use dots for OTLP labels

- .github/workflows/publish_lib_to_npm.yml
We haven't built them, so it breaks because of that. Alternatively, we could build and test them too, but since they're independent I don't think it'll add much (except minutes spent on the CI).
> Don't test Parcel and TS plugins before releasing lib

- CHANGELOG.md
- CONTRIBUTING.md
In addition to the `CHANGELOG.md`, please review the release announcement as well:
***
This release features full compliance with the [Autometrics v1.0.0 specification](https://github.com/autometrics-dev/autometrics-shared/blob/main/specs/autometrics_v1.0.0.md) as well as first-class [Deno](https://deno.com/) support. Also, our decorators have been updated to match the [Stage 3 ECMAScript decorators proposal](https://github.com/tc39/proposal-decorators).
In order to match the full Autometrics specification, we implemented the following features and changes:
* Decorators now have support for skipping individual methods when decorating a class. Just decorate the method you wish to exclude with `@Autometrics({ skip: true })`.
* We added support for the `service.name` label.  The service name …
> Update CHANGELOG + release announcement

- justfile
I *think* we used plain `npm publish` before, so it is probably configured for that. Anyway, we'll test it with the next release, since I don't want to create a new tag, or we'll also publish the Deno version multiple times.
> Change publish command

- packages/autometrics/src/platform.node.ts
after instrumenting my node / ts server with autometrics, things seemed to be working just fine locally.
unfortunately when i deployed to my dev environment (kubernetes cluster) i saw my service spike in cpu utilization and the event loop would hang causing all requests to time out.
this made it difficult to debug since i was unable to reproduce locally initially. i found that i could reproduce this behavior if i built the docker image and ran the container locally. from there i was able to run node with profiling flags to get the v8 log output. this pointed me to the `readFileSync` call inside the `readClosest` function and the issue became clear. there is an unhandled case on the node platform that will result in an infinite while loop if no git repository is initialized (as is the case …
> fix an infinite loop which happens when autometrics is initialized in a node service without a git repository

- packages/autometrics/src/utils.ts
when using an IOC container that relies on the reflect-metadata package (like InversifyJS), all functions in the app which are injected at runtime are attributed to the reflect metadata module, rather than the actual file that they are in.
this fixes that.
before:
after:
> make getModulePath ignore reflect metadata module
